// flow-typed signature: 2c841ecc7387355ed0697f192eddee8e
// flow-typed version: <<STUB>>/es2040_v^1.2.5/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es2040'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'es2040' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es2040/example' {
  declare module.exports: any;
}

declare module 'es2040/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es2040/example.js' {
  declare module.exports: $Exports<'es2040/example'>;
}
declare module 'es2040/index' {
  declare module.exports: $Exports<'es2040'>;
}
declare module 'es2040/index.js' {
  declare module.exports: $Exports<'es2040'>;
}
declare module 'es2040/test.js' {
  declare module.exports: $Exports<'es2040/test'>;
}
