// flow-typed signature: c702219226cadffb5d593f4011224e5b
// flow-typed version: <<STUB>>/nanobus_v^2.2.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nanobus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nanobus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nanobus/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nanobus/index' {
  declare module.exports: $Exports<'nanobus'>;
}
declare module 'nanobus/index.js' {
  declare module.exports: $Exports<'nanobus'>;
}
declare module 'nanobus/test.js' {
  declare module.exports: $Exports<'nanobus/test'>;
}
